version: '1'

services:
    framework:
        build: .
        working_dir: /var/www/
        restart: unless-stopped
        stdin_open: true
        volumes:
            - "../:/var/www"
        networks:
            - backend
networks:
    backend: